### ISSUE TITLE
Skipping engine check

### ISSUE THREAD

**Issue by sethtroisi** [mattheww/gomill#11]
I'm starting big tournaments with hundreds of players which each take a couple of seconds to start (LZ needs to read a 50+ mb files from disk). I thing it's reasonable to check all the engines the first time but when I resume a partially played tournament it's frustrating to have to wait.

I have a couple of ideas 
1. Skip engines that have finished all games in their matchups
1. adding a "skip_engine_check" either as an option in the control file or to ringmaster
1. skip engines that have completed games already played in a matchup.
1. if > X players only check Y random engines.

**Comment by mattheww** [comment]
Number 2 seems like the natural thing to do.
