### ISSUE TITLE
sgf coordinates -> ij coordinates

### ISSUE THREAD

**Issue by serhii-havrylov** [mattheww/gomill#2]
Hi!
I am struggling to understand [this](https://github.com/mattheww/gomill/blob/master/gomill/sgf_properties.py#L50) line of code. It seems to me that according to sgf [documentation](http://www.red-bean.com/sgf/go.html) it should be `row = ord(row_s) - 97`. Would you please explain it to me?

**Comment by traveller42** [comment]
gomill uses a 0-based internal representation with A1 = (0, 0).

A19 is SGF "aa" which is (0,18) for gomill internal representation.

row = size - ord(row_s) + 96
row = 19 - ord("a") + 96
row = 19 - 97 + 96
row = 19 - 1
row = 18

**Comment by sergii-gavrylov** [comment]
Hm, this is strange, and what is the reason for such representation?

**Comment by traveller42** [comment]
I'm not the original author, but A1 = (0, 0) was at least one of the ways to store the data.

Might be as simple as which translation was made first.

**Comment by mattheww** [comment]
[GTP](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION000311000000000000000) puts the origin in the bottom-left, while SGF puts it in the top-left. So whatever I did could match at most one of them.

GTP's coordinate system is also the usual one in the Latin-alphabet world (eg it's what IGS and KGS use). I think it goes back to Oscar Korschelt.

(And yes, gomill supported GTP before SGF.)
