### ISSUE TITLE
Incorrect version check when AQ returns a version string of "2.0"

### ISSUE THREAD

**Issue by bixbyr** [mattheww/gomill#5]
The authors of AQ return the version string as "2.0" instead of 2, so the version check fails incorrectly with a compatible client.

https://github.com/mattheww/gomill/blob/01b6b78d9948c494edce62b41a9eaf3ef0f3c106/gomill/gtp_controller.py#L636

**Comment by mattheww** [comment]
AQ is definitely Doing it Wrong, then (`version` can be any old string, but `protocol_version` should be an int).

It should be easy enough to work around it in gomill anyway, though, so I'll do that.

**Comment by bixbyr** [comment]
Yeah, I know it's AQ's fault but I wasn't sure how likely I was to get anywhere with filing an issue with them. Thanks for being willing to interoperate with something slightly out of spec.

**Comment by mattheww** [comment]
The workaround is released in v0.8.2.
