### ISSUE TITLE
Cmd windows error

### ISSUE THREAD

**Issue by ThomasCabaret** [mattheww/gomill#6]
Hello,
Any idea about the following error?

C:\Python27\Scripts>python ringmaster LeelaBinVs.ctl
running startup checks on all players
ringmaster: internal error
ValueError: preexec_fn is not supported on Windows platforms
traceback (most recent call last):
  C:\Python27\lib\site-packages\gomill\ringmaster_command_line.py:101 (run)
  C:\Python27\lib\site-packages\gomill\ringmaster_command_line.py:18 (do_run)
  C:\Python27\lib\site-packages\gomill\ringmasters.py:772 (check_players)
  C:\Python27\lib\site-packages\gomill\game_jobs.py:443 (check_player)
  C:\Python27\lib\site-packages\gomill\gtp_controller.py:407 (__init__)
  C:\Python27\lib\subprocess.py:626 (__init__)
failing line:
raise ValueError("preexec_fn is not supported on Windows "

**Comment by mattheww** [comment]
Gomill has never run on Windows.

You could try this newfangled Windows Subsystem for Linux thing.
