### ISSUE TITLE
please make windows version asap

### ISSUE THREAD

**Issue by hydrogenpi** [mattheww/gomill#7]
please make windows version asap

**Comment by mattheww** [comment]
I have no plans to port gomill to Windows.

That said, some parts would probably be easy to make work.

I expect the SGF code works on Windows already, and the GTP code probably would only need a bit of tweaking around the `SIGPIPE` handling and the `os.wait4()` call, if someone wants to try it.

For the ringmaster, anyone trying this would need to rework the keyboard handling that checks for a graceful exit request, and do something about the code that updates the status by renaming a new file over the existing one. And of course there may be further complications I haven't thought of.
