### ISSUE TITLE
Support for overriding player name

### ISSUE THREAD

**Issue by sethtroisi** [mattheww/gomill#9]
It would be useful for me to be able to change the SGF player name. I use it for for [my giant crosstable](https://cloudygo.com/cross-eval/eval-graphs) and it would be nice to have different leela networks return different names.

Currently SGFs look like this
```
C[Event: minigo-leela
...
Black minigo-v9-369 minigo-000369-warrior.pb
White leela-zero-d351f06e Leela Zero:0.15]
...
PB[minigo-000369-warrior.pb]PW[Leela Zero:0.15]
```

the root comment is generated here using the name (from the control file)
Where as the SGF PW and PB are generate with gtp name/version here[[1]](https://github.com/mattheww/gomill/blob/master/gomill/gtp_games.py#L570)[[2]](https://github.com/mattheww/gomill/blob/master/gomill/gtp_controller.py#L854)

**Comment by mattheww** [comment]
I think it would be easy to implement a new Player configuration argument that overrides the name used for the SGF file (and maybe in other places where it appears).

Alternatively I could make the ringmaster unconditionally add a couple of new private SGF properties to each file, containing the player codes (like `leela-zero-d351f06e` in your example).

Would that be more useful for you?

**Comment by mattheww** [comment]
Sure. I don't think there's any need for `gtp_games.make_sgf()` to change. You should be able to just have `Game_job._make_sgf()` overwrite what that put in `PB` and `PW`, if the new Player attribute is set.

**Comment by sethtroisi** [comment]
@mattheww I have a couple of pulls open. Would love for you to take a look.

**Comment by mattheww** [comment]
Sure, I should have some time this weekend.

**Comment by mattheww** [comment]
This looks good, but I think it's hard for the user to guess what `override_name` means. As it only affects SGF files I think it would be good to put 'sgf' somewhere in the setting name.

What do you think of using `sgf_player_name_from_gtp`, defaulting to True for the old behaviour?

**Comment by sethtroisi** [comment]
That's a reasonable name. I can update the code.

**Comment by sethtroisi** [comment]
Updated to new name.

**Comment by sethtroisi** [comment]
I updated to the new name, could you take another look?

**Comment by mattheww** [comment]
Thanks, I've merged this. I'll make a release sometime soon.

**Comment by sethtroisi** [comment]
Thanks for merging thisv

We (the minigo team) love ringmaster.
We use it a lot and it's super awesome
